---
title: "Rapport Uncancode n°1 :\n FIRSTDIG - Pour aller plus loin  ( Bonus )"
output: html_document
Date: "2022-10-30"
---

```{r import}
library('ggplot2')
```

# FristDigit
```{r}
#Écrire une fonction Cor qui donne le coefficient de corrélation avec la loi de Benford en base b pour un pour un vecteur x de chiffres de poids fort.

#import du module firstdigit
FirstDigit <- function(n,base){
  
  if  (n==0) return(0)
  n<-abs(n)
  while (!(n<base && n>=1)){
    
    if (n<1) n<-n*base
    if (n>base) n<-n/base
    
  }
  n<-as.integer(n)
  return(n)
  
}
```

# FirstDifit_vect


```{r}
FirstDigit_vec<-function(vect_entree,base){
  return(sapply(vect_entree,FirstDigit,base))
}


```

# Benford Law

```{r}

#import de la loi de benford

BenfordLaw <- function(x, base = 10) {
  return((log(x+1, base) - log(x, base)))}


#input
#Cor(x = 1:9, base = 10)
#Cor(x = c(1, 1, 1, 1, 2, 2, 2, 3, 3), base = 4)
#output
#NA
#Message d'avis :
#Dans cor(y, z) : l'écart type est nul
#0.9719616
#calcul de la corrélation


PlotBenfordLaw <- function(base = c( 3, 4, 8, 10, 12, 16)) {
  p <- ggplot2::ggplot() + ggplot2::xlim(1, max(base) -1)  +  ggplot2::theme(text = ggplot2::element_text(size = 20))
  for(b in base) {
    p <- p + ggplot2::stat_function(fun=BenfordLaw, xlim = c(1, b - 1), args = list(base = b), ggplot2::aes_string(colour=b))
  }
  return(p)
}


```

# convert comptage
```{r}
convert_comptage<-function(vect_entree,base){
  res<-rep(0,(base-1))
  for (i in vect_entree){
    res[i]<-res[i]+1
  }
  res<-res/length(vect_entree)
    return(res)
}
#cat(convert_comptage(c(1,1,1,1,2,2,2,3,3),4),'\n')
#cat(convert_comptage(1:9,10),'\n')
```

# Cor
```{r}
Cor<-function(x,base){
  #calcul de la loi de benford
  cat(x,'\n')
  x<-convert_comptage(x,base)
  cat(x,'\n')
  
  #calcul de la loi de benford pour les chiffres de poids fort
  
  
  loi_benford_poids_fort<-BenfordLaw(1:(base-1),base)
  #calcul de la corrélation
  cat(loi_benford_poids_fort,"\n",x,"\n")
  r<-cor(loi_benford_poids_fort,x)
  cat(r,"\n")
  return(r)
}

```

# Test cor
```{r}
testCor<-function(){
  #cat("Test de la fonction FirstDigit_vec avec l'entrée ",entree," et la base ",entree[2],"\n")
  stopifnot(
    is.na(Cor(x = 1:9, base = 10))
    #Cor(x = c(1, 1, 1, 1, 2, 2, 2, 3, 3), base = 4)==0.9719616
  )
}
#Cor(x = c(1, 1, 1, 1, 2, 2, 2, 3, 3), base = 4)
#cat(1:9,'\n')
#Cor(x = 1:9, base = 10)
#testCor()
```

# Hist
```{r}
Hist <- function(x, base) {
  ## Build text elements
  title <- paste0(
    "Premiers chiffres en base ", base,
    "\nCorrélation avec Benford : ",  Cor(x, base)
  )
  df <- data.frame(digit = x)
  ggplot2::ggplot(df,  ggplot2::aes(x=digit)) +
    ggplot2::geom_histogram(ggplot2::aes(y =..density..), color="black", fill="white", binwidth = 1) +
    ggplot2::stat_function(fun=BenfordLaw, args = list(base = base), ggplot2::aes(color="Benford Law")) +
    ggplot2::ggtitle(title) +
    ggplot2::theme(text = ggplot2::element_text(size = 20))
}

```

# test validité (process Benford)
```{r}
#Écrire une fonction ProcessBenford qui prend en argument un vecteur numérique x et une base base et effectue les étapes suivantes.
#Elle vérifie la validité de ses arguments.
#Elle calcule le vecteur des premiers chiffres des nombres de x écrit en base base.
#Elle renvoie un histogramme.
testvalidite<-function(x,base){
  if (base<2){
    cat("La base doit être supérieure ou égale à 2 \n")
    return (FALSE) }
  if (length(x)==0) {
    cat("x doit être non vide \n")
    return (FALSE)}
  if (any(x<0)) { 
    cat("x doit être positif") 
    return (FALSE) }
  if (any(x==0)) {
    cat("x doit être non nul") 
    return (FALSE) }
  return(TRUE)
}
```
# Process Benford
```{r}
ProcessBenford<-function(x,base){
  if (typeof(x)=="list") x <- unlist(x)
  #Elle vérifie la validité de ses arguments.
  if (testvalidite(x,base)==FALSE) return(NA)
  #Elle calcule le vecteur des premiers chiffres des nombres de x écrit en base base.
  premiers_chiffres<-FirstDigit_vec(x,base)
  #Elle renvoie un histogramme.
  
  Hist(premiers_chiffres,base)}

```

# 1.4.8

```{r}
x <- sample(1:10000 ,replace = TRUE ,size = 10000)
y <- sample(1:10000 ,replace = TRUE ,size = 10000)
#ProcessBenford(x,base = 10)
#ProcessBenford(y,base = 10)
```


# appelle de fonction
```{r}
ProcessBenford(1:9,10)
ProcessBenford(c(1, 1, 1, 1, 2, 2, 2, 3, 3), 4)
PlotBenfordLaw()
Hist(x = c(1, 1, 1, 1, 2, 2, 2, 3, 3),4)
```

